### ISSUE TITLE
No longer working 

### ISSUE THREAD

**Issue by Kai0KenX20** [Tekk-Know/RazerBatteryTaskbar#2]
not quite sure what happen this used to work no problem but now it always displays my battery at 0%
![Untitled2](https://user-images.githubusercontent.com/49903983/236341117-a838bedd-ab7c-45f9-b39a-235826e5fbdd.png)

**Comment by GothicIII** [comment]
That's on synapse. I pulled out wireshark with usbpcap and analyzed the traffic. 

When 'await mouse.controlTransferOut()' is triggered, the program sends out a SET_REPORT Request which is answered with a SET_REPORT Response. After that follows a GET_REPORT Request and the response got the battery data we need.

If Razer synapse is running and busy with the device (e.g. sending custom light effects) then the GET_REPORT request is never send! It is sufficient to just toggle off brightness and the battery indicator is working again.

I don't know anything about the USB spec. Maybe Razer is reclaiming the interface and libusb is unable to send the request.


This is such a letdown. I desperatly want a battery indicator for the stream deck since but I need a working code base :( Synapse low battery status message is broken beyond repair, my devices just shut off without any warning...

**Comment by Tekk-Know** [comment]
On occasion the meter will show 0, it should update correctly after a polling or two.
